version: "3.7"
services:
  carzar-backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=carzar_db
      - POSTGRES_PASSWORD=password
    networks:
      - spring-postgres
  carzar-db:
    image: postgres
    restart: always
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=carzar_db
      - POSTGRES_PASSWORD=password
    expose:
      - "5432"
    ports:
      - "5433:5432"
networks:
  spring-postgres:
