CREATE TABLE CAR_TYPES
(
    CAR_TYPE_ID   SERIAL PRIMARY KEY,
    CAR_TYPE_NAME VARCHAR(255)
);

CREATE TABLE CAR_MODELS
(
    CAR_MODEL_ID   SERIAL PRIMARY KEY,
    CAR_MODEL_NAME VARCHAR(255),
    CAR_TYPE_ID INTEGER,
    CONSTRAINT FK_CAR_TYPE
        FOREIGN KEY (CAR_TYPE_ID)
            REFERENCES CAR_TYPES (CAR_TYPE_ID)
);

CREATE TABLE BODY_TYPES
(
    BODY_TYPE_ID   SERIAL PRIMARY KEY,
    BODY_TYPE_NAME VARCHAR(255),
    CAR_TYPE_ID    INTEGER,
    CONSTRAINT FK_CAR_TYPE
        FOREIGN KEY (CAR_TYPE_ID)
            REFERENCES CAR_TYPES (CAR_TYPE_ID)
);

CREATE TABLE CARS
(
    CAR_ID       SERIAL PRIMARY KEY,
    CAR_TYPE_ID  INTEGER,
    CAR_MODEL_ID INTEGER,
    BODY_TYPE_ID INTEGER,
    CONSTRAINT FK_CAR_MODEL
        FOREIGN KEY (CAR_MODEL_ID)
            REFERENCES CAR_MODELS (CAR_MODEL_ID),
    CONSTRAINT FK_CAR_TYPE
        FOREIGN KEY (CAR_TYPE_ID)
            REFERENCES CAR_TYPES (CAR_TYPE_ID),
    CONSTRAINT FK_BODY_TYPE
        FOREIGN KEY (BODY_TYPE_ID)
            REFERENCES BODY_TYPES (BODY_TYPE_ID)
);

CREATE TABLE USERS
(
    USER_ID          SERIAL PRIMARY KEY,
    USER_FIRST_NAME  VARCHAR(255),
    USER_SECOND_NAME VARCHAR(255),
    USER_EMAIL       VARCHAR(255),
    PASSWORD         VARCHAR(255),
    PHONE_NUMBER     VARCHAR(255)
);

CREATE TABLE ROLES
(
    ROLE_ID   SERIAL PRIMARY KEY,
    ROLE_NAME VARCHAR(255)
);

CREATE TABLE USER_ROLES
(
    USER_ID INTEGER,
    ROLE_ID INTEGER,
    CONSTRAINT FK_USER
        FOREIGN KEY (USER_ID)
            REFERENCES USERS (USER_ID),
    CONSTRAINT FK_ROLE
        FOREIGN KEY (ROLE_ID)
            REFERENCES ROLES (ROLE_ID),
    PRIMARY KEY (USER_ID, ROLE_ID)
);

CREATE TABLE ADVERTISEMENTS
(
    ADVERTISEMENT_ID          SERIAL PRIMARY KEY,
    ADVERTISEMENT_DESCRIPTION VARCHAR(255),
    PRICE                     INTEGER,
    USER_ID                   INTEGER,
    CAR_ID                    INTEGER,
    MILEAGE                   INTEGER,
    COLOR                     VARCHAR(255),
    CONSTRAINT FK_CAR
        FOREIGN KEY (CAR_ID)
            REFERENCES CARS (CAR_ID),
    CONSTRAINT FK_USER
        FOREIGN KEY (USER_ID)
            REFERENCES USERS (USER_ID)
);


CREATE TABLE PHOTOS
(
    PHOTO_ID         SERIAL PRIMARY KEY,
    PHOTO_NAME       VARCHAR(255),
    ADVERTISEMENT_ID INTEGER,
    CONSTRAINT FK_ADVERTISEMENT
        FOREIGN KEY (ADVERTISEMENT_ID)
            REFERENCES ADVERTISEMENTS (ADVERTISEMENT_ID)
);





