INSERT INTO USERS (USER_FIRST_NAME, USER_SECOND_NAME, USER_EMAIL, PASSWORD, PHONE_NUMBER)
    VALUES ('Bob', 'Bobich', 'bobich@gmail.com', 'bobich', '+380111111111');

INSERT INTO USERS (USER_FIRST_NAME, USER_SECOND_NAME, USER_EMAIL, PASSWORD, PHONE_NUMBER)
    VALUES ('Tim', 'Timich', 'timich@gmail.com', 'timich', '+380222222222');